### PR TITLE
take unnecessary transactions out of the hbase tests.

### PR DESCRIPTION
**Pull request by nlacasse**

### CODE REVIEW

**Comment by ZackGC** [comment]
After talking with @mbroecheler last night about why automatic transaction were made in the first place, I am sticking with the decision not to support automatic transactions. Originally, auto transactions were made to support people who didn't want to think about what they were doing with their databases in terms of transactions. They wanted to do all of their actions and then maybe commit some stuff later on. While that might be useful for quickly hacking things together, if this project starts tackling threading via clojure features, I could see a ton of headaches appearing without much benefit. So, I am saying that if you are modifying a persistent database, all of your actions need to be inside of transact! More so, there should be no need for hermes to call refresh/transact! inside any of it's functions. (@nlacasse, this isn't anything that we haven't already talked about, but I wanted to write it all out right now. )

**Comment by nlacasse** [comment]
@ZackGC Sounds good to me.

Since we don't want to call "refresh" or "transact" ourselves, can you merge #14, which takes out the "refresh"es.

Also, if Hermes does enforce the use of transact!s, we should issue some better error when the user is doing stuff outside of a transact!.  Right now they will get an error about addVertex, which is a bit misleading.

**Comment by nlacasse** [comment]
@ZackGC Also, #12 fixes a bug where the tests had code that was running NOT in a transaction, which causes failures when run on an empty hbase.

**Comment by ZackGC** [comment]
@nlacasse All tested and merged. I made that comment and then lunch showed up before I could finish up. 

I'm still thinking about the best way to enforce transactions. Maybe use [sleight](https://github.com/ztellman/sleight) or some custom macro or function to have every function in the edge/type/vertex namespaces in hermes check to see if _graph_ is in memory or a transaction.

**Pull request closed without merging**
